# Dockerfile for gRPC Go
# The one in Git is pretty old - updated https://github.com/grpc/grpc-docker-library/pull/69
# Build command docker build --build-arg  http_proxy=http://10.158.100.6:8080 
# --build-arg https_proxy=http://10.158.100.6:8080  -t grpc/go:1.12 -f Dockerfile.build .
FROM golang:1.12

# install protobuf from source
ENV PB_VER 3.9.1 
ENV PB_URL https://github.com/google/protobuf/releases/download/v${PB_VER}/protoc-${PB_VER}-linux-x86_64.zip
RUN apt-get update && apt-get install -y unzip && mkdir -p /tmp/protoc && \
  curl -L ${PB_URL} > /tmp/protoc/protoc.zip && \
  cd /tmp/protoc && \
  unzip protoc.zip && \
  cp /tmp/protoc/bin/protoc /usr/local/bin &&  \
  cp -R /tmp/protoc/include/* /usr/local/include && \
  chmod go+rx /usr/local/bin/protoc && \
  cd /tmp && \
  rm -r /tmp/protoc

# Get the source from GitHub
ENV  GO111MODULE on
RUN go get google.golang.org/grpc@v1.22.1
# Install protoc-gen-go
RUN go get github.com/golang/protobuf/protoc-gen-go@v1.2.0